# Data prep

Esse notebook desloca os dados em um ano ou um mÃªs, dependendo do indicadorimport pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
PATH="https://raw.githubusercontent.com/LeiteJu/TCC/main/dados/input/"

x = pd.read_csv(f"{PATH}input.csv")
x = x.sort_values(["data", "estados"])

y = pd.read_csv(f"{PATH}target.csv")
y['data'] = pd.to_datetime(y['data'])

In [6]:
ANUAL = [ 'pib_pc', 'pib_pmc', 'pib_pcpt', 'pib_cc',
          'populacao', 'idh_l', 'idh_r', 'idh_e', 'desemprego']
MENSAL = ['incc', 'ipca', 'igp', 'selic', 'nfsp',
           'estoque', 'producao', 'preco_ton', 'preco_saco',
           'preco_kg']

In [34]:
NULL = -1

In [7]:
df = x.copy()

In [12]:
df['data'] = pd.to_datetime(df['data'])

In [14]:
df = df[df['data'].dt.year >= 2002]

In [22]:
df = pd.merge(df, y, how='left', on=['data', 'estados'])

In [25]:
df_sorted = df.sort_values(by=["estados", "data"]).copy()
for estado in df.estados.unique():
    indexes = df_sorted[df_sorted["estados"] == estado].index
    df_sorted.loc[indexes, ANUAL] = df_sorted.loc[indexes, ANUAL].shift(12)
    df_sorted.loc[indexes, MENSAL] = df_sorted.loc[indexes, MENSAL].shift(1)

In [28]:
df_sorted.head(15)

,estados,data,pib_pc,pib_pmc,pib_pcpt,pib_cc,populacao,incc,ipca,igp,...,idh_r,idh_e,nfsp,estoque,desemprego,producao,preco_ton,preco_saco,preco_kg,consumo
0,AC,2002-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,AC,2002-02-01,NaN,NaN,NaN,NaN,NaN,0.36,0.52,0.19,...,NaN,NaN,1.90,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
54,AC,2002-03-01,NaN,NaN,NaN,NaN,NaN,0.58,0.88,0.18,...,NaN,NaN,1.79,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
81,AC,2002-04-01,NaN,NaN,NaN,NaN,NaN,0.55,1.49,0.11,...,NaN,NaN,1.79,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
108,AC,2002-05-01,NaN,NaN,NaN,NaN,NaN,0.33,2.30,0.70,...,NaN,NaN,1.65,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
135,AC,2002-06-01,NaN,NaN,NaN,NaN,NaN,2.53,2.51,1.11,...,NaN,NaN,1.55,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
162,AC,2002-07-01,NaN,NaN,NaN,NaN,NaN,0.57,2.94,1.74,...,NaN,NaN,1.77,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
189,AC,2002-08-01,NaN,NaN,NaN,NaN,NaN,0.29,4.17,2.05,...,NaN,NaN,1.98,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
216,AC,2002-09-01,NaN,NaN,NaN,NaN,NaN,1.00,4.85,2.36,...,NaN,NaN,1.77,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
243,AC,2002-10-01,NaN,NaN,NaN,NaN,NaN,0.71,5.60,2.64,...,NaN,NaN,2.15,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
270,AC,2002-11-01,NaN,NaN,NaN,NaN,NaN,1.13,6.98,4.21,...,NaN,NaN,2.18,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
297,AC,2002-12-01,NaN,NaN,NaN,NaN,NaN,2.45,10.22,5.84,...,NaN,NaN,2.46,6.098524e+06,NaN,NaN,NaN,NaN,NaN,NaN
324,AC,2003-01-01,434223.352964,228569.188542,0.739806,506500.171013,586942.0,1.70,12.53,2.70,...,0.612,0.325,3.46,6.098524e+06,6.582788,NaN,NaN,NaN,NaN,3260.0
351,AC,2003-02-01,434223.352964,228569.188542,0.739806,506500.171013,586942.0,1.51,2.25,2.17,...,0.612,0.325,3.59,6.172460e+06,6.582788,-999.0,NaN,NaN,NaN,2191.0
378,AC,2003-03-01,434223.352964,228569.188542,0.739806,506500.171013,586942.0,1.39,3.86,1.59,...,0.612,0.325,3.84,6.172460e+06,6.582788,-999.0,NaN,NaN,NaN,2154.0

In [36]:
df_sorted = df_sorted.fillna(NULL)

In [38]:
df_sorted = df_sorted[df_sorted['data'].dt.year >= 2003]

In [43]:
df_sorted.to_csv('../dados/input/processado.csv', index=False)